version: '3.8'

services:
  db:
    image: mysql
    container_name: sivoting-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sivotingdb
      MYSQL_USER: sivoting
      MYSQL_PASSWORD: 5X(Eef3CoH3_(q9A4x
      MYSQL_ROOT_PASSWORD: root_password
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sivoting-net

  server:
    build: ./serverapp
    container_name: sivoting-server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/sivotingdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: sivoting
      SPRING_DATASOURCE_PASSWORD: 5X(Eef3CoH3_(q9A4x
      SERVER_PORT: 8080
      SERVER_BASE_URL: http://server:8080
      CORS_ALLOWED_ORIGINS: http://client:8081
    ports:
      - "8080:8080"
    networks:
      - sivoting-net

  client:
    build: ./clientapp
    container_name: sivoting-client
    restart: unless-stopped
    depends_on:
      - server
    environment:
      SERVER_PORT: 8081
      API_BASE_URL: http://server:8080/api
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    networks:
      - sivoting-net

networks:
  sivoting-net:
    driver: bridge

volumes:
  db-data:
